if exists (select 1 from sys.databases where name='QuanLyBenhVien')
begin
	drop database QuanLyBenhVien
end
create database QuanLyBenhVien;
use QuanLyBenhVien;

/*	========================================PHẦN TẠO BẢNG========================================		*/

CREATE TABLE BENHNHAN(
MABN VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
GIOITINH NVARCHAR(10),
DIACHI NVARCHAR(255),
SOBHYT CHAR(20) UNIQUE
);
CREATE TABLE THUOC(
MATHUOC INT IDENTITY(1,1) PRIMARY KEY,
TENTHUOC NVARCHAR(100) NOT NULL,
DONVI NVARCHAR(20),
GIA DECIMAL(18,2) NOT NULL,
);
CREATE TABLE KHOA (
    MAKHOA VARCHAR(10) NOT NULL,
    TENKHOA NVARCHAR(100) NOT NULL,
    VITRI NVARCHAR(100),
    SODIENTHOAI VARCHAR(15),
    TRUONGKHOA VARCHAR(10),
    NGAYTHANHLAP DATE,
    CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR(10) NOT NULL,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(200),
    SODT VARCHAR(15),
    MAKHOA VARCHAR(10),
    CHUCVU NVARCHAR(50),
    CONSTRAINT PK_NV PRIMARY KEY (MANV),
    CONSTRAINT FK_NV_KHOA FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);

CREATE TABLE PHONGBENH (
    MAPHONG INT IDENTITY(1,1) NOT NULL,
    TENPHONG NVARCHAR(100),
    LOAIPHONG NVARCHAR(50),
    MAKHOA VARCHAR(10),
    SUCCHUA INT,
    GIAPHONG DECIMAL(10,2),
    CONSTRAINT PK_PB PRIMARY KEY (MAPHONG),
    CONSTRAINT FK_PB_KHOA FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);
-- DO BẢNG NHANVIEN TẠO SAU BẢNG KHOA NÊN CẦN THÊM KHÓA NGOẠI SAU ĐÓ
-- NỐI KHOA(TRUONGKHOA) VỚI NHANVIEN(MANV)
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_TRUONGKHOA FOREIGN KEY (TRUONGKHOA)
REFERENCES NHANVIEN(MANV);

CREATE TABLE NHAPVIEN (
	MANHAPVIEN VARCHAR(10) PRIMARY KEY,
	MABN VARCHAR(10) NOT NULL,
	MAPHONG INT NOT NULL,
	NGAYNHAPVIEN DATETIME NOT NULL,
	NGAYXUATVIEN DATETIME,
	LYDONHAPVIEN NVARCHAR(MAX),
	CONSTRAINT FK_NHAPVIEN_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
	CONSTRAINT FK_NHAPVIEN_PHONGBENH FOREIGN KEY (MAPHONG) REFERENCES PHONGBENH(MAPHONG),
);

-- Bảng HỒ SƠ BỆNH ÁN --> gọi tắt là "hồ sơ" (HOSO)
CREATE TABLE HOSO (
	MAHS VARCHAR(10) PRIMARY KEY,
	MANHAPVIEN VARCHAR(10) NOT NULL,
	MABACSI VARCHAR(10) NOT NULL,
	CHUANDOAN NVARCHAR(MAX) NOT NULL,
	NGAYKHAM DATETIME NOT NULL,
	HUONGDIEUTRI NVARCHAR(MAX),
	CONSTRAINT FK_HOSO_NHAPVIEN FOREIGN KEY (MANHAPVIEN) REFERENCES NHAPVIEN(MANHAPVIEN),
	CONSTRAINT FK_HOSO_NHANVIEN FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV),
);

-- Bảng TOA THUỐC
CREATE TABLE TOATHUOC (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATOA VARCHAR(10) NOT NULL,
	MAHS VARCHAR(10) NOT NULL,
	MATHUOC INT NOT NULL,
	SOLUONG INT NOT NULL,
	LIEULUONG NVARCHAR(100),
	CACHDUNG NVARCHAR(255),
	CONSTRAINT FK_TOATHUOC_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
	CONSTRAINT FK_TOATHUOC_THUOC FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC),
);

/*	========================================xxxxxx========================================		*/