create database QuanLyBenhVien;
use QuanLyBenhVien;
/*	========================================PHẦN TẠO BẢNG========================================		*/
CREATE TABLE BENHNHAN(
MABN VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
GIOITINH NVARCHAR(10),
DIACHI NVARCHAR(255),
SOBHYT CHAR(20) UNIQUE
);
CREATE TABLE THUOC(
MATHUOC INT IDENTITY(1,1) PRIMARY KEY,
TENTHUOC NVARCHAR(100) NOT NULL,
DONVI NVARCHAR(20),
GIA DECIMAL(18,2) NOT NULL,
);
