USE master;
GO

-- Cấu hình cơ sở dữ liệu về SINGLE_USER để ngắt toàn bộ các kết nối đang hoạt động
IF EXISTS (SELECT 1 FROM sys.databases WHERE name='QuanLyBenhVien')
BEGIN
    ALTER DATABASE QuanLyBenhVien SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QuanLyBenhVien;
END

GO
CREATE DATABASE QuanLyBenhVien;
GO

USE QuanLyBenhVien;
GO

/* ======================================== PHẦN TẠO BẢNG ======================================== */

-- 1. Bảng BENHNHAN (Độc lập)
CREATE TABLE BENHNHAN(
    MABN VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(255),
    SOBHYT CHAR(10) UNIQUE,
    SDT VARCHAR(20),
    EMAIL VARCHAR(100),
    CCCD CHAR(16) UNIQUE,
    NGAYNHAPHS DATE,
    NGUOITHANLIENHE NVARCHAR(100),
    SDTNGUOITHAN VARCHAR(20)
);

-- 2. Bảng THUOC (Độc lập)
CREATE TABLE THUOC(
    MATHUOC INT IDENTITY(1,1) PRIMARY KEY,
    TENTHUOC NVARCHAR(100) NOT NULL,
    DONVI NVARCHAR(20),
    GIA DECIMAL(18,2) NOT NULL DEFAULT 0,
    HAMLUONG NVARCHAR(100),
    HOATCHAT NVARCHAR(255),
    HANSUDUNG DATE,
    SOLUONGTON INT,
    TRANGTHAI NVARCHAR(20)
);

-- 3. Bảng LOAIPHONG (Độc lập - Cần tạo trước PHONGBENH)
CREATE TABLE LOAIPHONG (
    MALOAIPHONG VARCHAR(10) PRIMARY KEY,
    TENLOAIPHONG NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(MAX),
    GIACOBAN DECIMAL(18, 2) NOT NULL DEFAULT 0 
);

-- 4. Bảng KHOA (Tạo trước nhưng chưa có Khóa ngoại Trưởng khoa vì bảng NHANVIEN chưa được tạo)
CREATE TABLE KHOA (
    MAKHOA VARCHAR(10) NOT NULL,
    TENKHOA NVARCHAR(100) NOT NULL,
    VITRI NVARCHAR(100),
    SODIENTHOAI VARCHAR(15),
    TRUONGKHOA VARCHAR(10), -- Sẽ add CONSTRAINT sau khi tạo bảng NHANVIEN
    NGAYTHANHLAP DATE,
    EMAILKHOA VARCHAR(50),
    GHICHU NVARCHAR(50),
    CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);

-- 5. Bảng NHANVIEN (Tham chiếu đến KHOA)
CREATE TABLE NHANVIEN (
    MANV VARCHAR(10) NOT NULL,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(200),
    SODT VARCHAR(15),
    MAKHOA VARCHAR(10), -- Sửa lại kiểu VARCHAR(10) đồng bộ với bảng KHOA
    CHUCVU NVARCHAR(50),    
    EMAIL VARCHAR(50),
    NGAYVAOLAM DATE,
    BANGCAP VARCHAR(50),
    CHUYENMON VARCHAR(50),
    TRANGTHAI NVARCHAR(50),
    CONSTRAINT PK_NV PRIMARY KEY (MANV),
    CONSTRAINT FK_NV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

-- Bây giờ có thể thêm Khóa ngoại cho TRUONGKHOA trong bảng KHOA
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_TRUONGKHOA FOREIGN KEY (TRUONGKHOA) REFERENCES NHANVIEN(MANV);

-- 6. Bảng PHONGBENH (Tham chiếu đến KHOA và LOAIPHONG)
CREATE TABLE PHONGBENH (
    MAPHONG INT IDENTITY(1,1) NOT NULL,
    TENPHONG NVARCHAR(100),
    MALOAIPHONG VARCHAR(10),
    MAKHOA VARCHAR(10),
    SUCCHUA INT,
    GIAPHONG DECIMAL(10,2),
    TRANGTHAI NVARCHAR(20),
    SOGIUONGTRONG INT,
    GHICHU NVARCHAR(50),
    CONSTRAINT PK_PB PRIMARY KEY (MAPHONG),
    CONSTRAINT FK_PB_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
    CONSTRAINT FK_PB_LOAIPHONG FOREIGN KEY (MALOAIPHONG) REFERENCES LOAIPHONG(MALOAIPHONG)
);

-- 7. Bảng DIEUTRINOITRU (Tham chiếu đến BENHNHAN, PHONGBENH, NHANVIEN)
CREATE TABLE DIEUTRINOITRU (
    MANOITRU VARCHAR(10) PRIMARY KEY,
    MABN VARCHAR(10) NOT NULL,
    MABACSI VARCHAR(10),
    MAPHONG INT, -- Sửa lại kiểu INT để khớp với PHONGBENH(MAPHONG)
    NGAYNHAPVIEN DATETIME NOT NULL,
    NGAYXUATVIEN DATETIME,
    LYDONHAPVIEN NVARCHAR(MAX) NOT NULL,
    TINHTRANGRAVIEN NVARCHAR(255),
    CONSTRAINT FK_DTNT_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    CONSTRAINT FK_DTNT_PHONGBENH FOREIGN KEY (MAPHONG) REFERENCES PHONGBENH(MAPHONG),
    CONSTRAINT FK_DTNT_BACSI FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV)
);

-- 8. Bảng HOSO (Tham chiếu đến DIEUTRINOITRU, BENHNHAN, NHANVIEN)
CREATE TABLE HOSO (
    MAHS VARCHAR(10) PRIMARY KEY,
    MANOITRU VARCHAR(10) NOT NULL,
    MABN VARCHAR(10) NOT NULL,
    MABACSI VARCHAR(10) NOT NULL,
    CHUANDOAN NVARCHAR(MAX) NOT NULL,
    TRIEUCHUNG NVARCHAR(MAX) NOT NULL,
    KETLUAN NVARCHAR(MAX),
    HUONGDIEUTRI NVARCHAR(MAX),
    NGAYKHAM DATETIME NOT NULL,
    TRANGTHAIHOSO NVARCHAR(50),
    CONSTRAINT FK_HOSO_DTNT FOREIGN KEY (MANOITRU) REFERENCES DIEUTRINOITRU(MANOITRU),
    CONSTRAINT FK_HOSO_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    CONSTRAINT FK_HOSO_NHANVIEN FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV)
);

-- 9. Bảng HOADONVIENPHI (Tạo trước bảng THANHTOAN và CHITIETVIENPHI)
CREATE TABLE HOADONVIENPHI (
    MAHOADON INT PRIMARY KEY,
    MABN VARCHAR(10) NOT NULL, 
    NGAYLAP DATETIME,
    TONGTIEN DECIMAL(18, 2) DEFAULT 0,
    TRANGTHAITHANHTOAN NVARCHAR(50), 
    GHICHU NVARCHAR(MAX),
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
);

-- 10. Bảng THANHTOAN (Tham chiếu đến HOADONVIENPHI)
CREATE TABLE THANHTOAN (
    MATHANHTOAN VARCHAR(20) PRIMARY KEY,
    MAHOADON INT NOT NULL,
    NGAYTHANHTOAN DATETIME NOT NULL,
    SOTIEN DECIMAL(18,2) NOT NULL,
    PHUONGTHUC NVARCHAR(50),
    TRANGTHAI NVARCHAR(50),
    CONSTRAINT FK_TT_HDVP FOREIGN KEY (MAHOADON) REFERENCES HOADONVIENPHI(MAHOADON)
);

-- 11. Bảng CHITIETVIENPHI (Tham chiếu đến HOADONVIENPHI)
CREATE TABLE CHITIETVIENPHI (
    MAHOADON INT NOT NULL,
    LOAICHIPHI NVARCHAR(100) NOT NULL,
    SOTIEN DECIMAL(14,2),
    MOTA NVARCHAR(255),
    PRIMARY KEY (MAHOADON, LOAICHIPHI),
    FOREIGN KEY (MAHOADON) REFERENCES HOADONVIENPHI(MAHOADON)
);

-- 12. Bảng DICHVUYTE (Độc lập)
CREATE TABLE DICHVUYTE (
    MADV INT NOT NULL,
    TENDV NVARCHAR(150),
    DONGIA DECIMAL(12,2),
    MOTA NVARCHAR(255),
    TRANGTHAI NVARCHAR(50),
    PRIMARY KEY (MADV)
);

-- 13. Bảng LICHHENKHAM (Sửa lại kiểu dữ liệu của MABN và MABACSI để liên kết đúng bảng)
CREATE TABLE LICHHENKHAM (
    MALICHHEN INT NOT NULL,
    MABN VARCHAR(10), -- Sửa lại VARCHAR(10) để khớp với BENHNHAN
    MABACSI VARCHAR(10), -- Sửa lại VARCHAR(10) và đổi tham chiếu sang NHANVIEN
    NGAYHEN DATE,
    GIOHEN TIME,
    TRANGTHAI NVARCHAR(50),
    GHICHU NVARCHAR(255),
    PRIMARY KEY (MALICHHEN),
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV) -- Tham chiếu chính xác đến bảng nhân viên (bác sĩ)
);

-- 14. Bảng LICHSUDIEUTRI (Tham chiếu đến HOSO và NHANVIEN)
CREATE TABLE LICHSUDIEUTRI (
    MALS VARCHAR(10) PRIMARY KEY,
    MAHS VARCHAR(10) NOT NULL,
    NGAYCAPNHAT DATETIME NOT NULL,
    NOIDUNG NVARCHAR(MAX) NOT NULL,
    MANV VARCHAR(10) NOT NULL,
    GHICHU NVARCHAR(255),
    CONSTRAINT FK_LSDT_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
    CONSTRAINT FK_LSDT_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- 15. Bảng CHI TIẾT DỊCH VỤ (Tham chiếu đến HOSO và DICHVUYTE)
CREATE TABLE CHITIETDICHVU (
    MAHS VARCHAR(10) NOT NULL,
    MADV INT NOT NULL,
    NGAYTHUCHIEN DATETIME NOT NULL,
    KETQUA NVARCHAR(MAX),
    CHIPHI DECIMAL(18,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (MAHS, MADV), 
    CONSTRAINT FK_CTDV_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
    CONSTRAINT FK_CTDV_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVUYTE(MADV)
);

-- 16. Bảng TOA THUỐC (Tham chiếu đến HOSO và THUOC)
CREATE TABLE TOATHUOC (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MATOA VARCHAR(10) NOT NULL,
    MAHS VARCHAR(10) NOT NULL,
    MATHUOC INT NOT NULL,
    SOLUONG INT NOT NULL,
    DONGIA DECIMAL(18,2) NOT NULL,
    THANHTIEN DECIMAL(18,2),
    LIEULUONG NVARCHAR(100) NOT NULL,
    CACHDUNG NVARCHAR(255),
    GHICHU NVARCHAR(MAX),
    CONSTRAINT FK_TOATHUOC_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
    CONSTRAINT FK_TOATHUOC_THUOC FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC)
);
/*     =========xxxxxx========================================		*/