CREATE TABLE BENHNHAN(
MABN VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
GIOITINH NVARCHAR(10),
DIACHI NVARCHAR(255),
SOBHYT CHAR(10) UNIQUE,
SDT VARCHAR(20),
EMAIL VARCHAR(100),
CCCD CHAR(16) UNIQUE,
NGAYNHAPHS DATE,
NGUOITHANLIENHE NVARCHAR(100),
SDTNGUOITHAN VARCHAR(20)
);
CREATE TABLE THUOC(
MATHUOC INT IDENTITY(1,1) PRIMARY KEY,
TENTHUOC NVARCHAR(100) NOT NULL,
DONVI NVARCHAR(20),
GIA DECIMAL(18,2) NOT NULL,
HAMLUONG NVARCHAR(100),
HOATCHAT NVARCHAR(255),
HANSUDUNG DATE,
SOLUONGTON INT,
TRANGTHAI NVARCHAR(20),
);