CREATE TABLE BENHNHAN(
MABN VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
GIOITINH NVARCHAR(10),
DIACHI NVARCHAR(255),
SOBHYT CHAR(10) UNIQUE,
SDT VARCHAR(20),
EMAIL VARCHAR(100),
CCCD CHAR(16) UNIQUE,
NGAYNHAPHS DATE,
NGUOITHANLIENHE NVARCHAR(100),
SDTNGUOITHAN VARCHAR(20)
);
CREATE TABLE THUOC(
MATHUOC INT IDENTITY(1,1) PRIMARY KEY,
TENTHUOC NVARCHAR(100) NOT NULL,
DONVI NVARCHAR(20),
GIA DECIMAL(18,2) NOT NULL DEFAULT 0,
HAMLUONG NVARCHAR(100),
HOATCHAT NVARCHAR(255),
HANSUDUNG DATE,
SOLUONGTON INT,
TRANGTHAI NVARCHAR(20),
);
CREATE TABLE LOAIPHONG (
    MALOAIPHONG VARCHAR(10) PRIMARY KEY,
    TENLOAIPHONG NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(MAX),
    GIACOBAN DECIMAL(18, 2) NOT NULL DEFAULT 0 
);
CREATE TABLE HOADONVIENPHI (
    MAHOADON INT PRIMARY KEY,
    MABN VARCHAR(10) NOT NULL, 
    NGAYLAP DATETIME,
    TONGTIEN DECIMAL(18, 2) DEFAULT 0,
    TRANGTHAITHANHTOAN NVARCHAR(50), 
    GHICHU NVARCHAR(MAX),
	FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
);