-- Thinh's

-- Bảng THANH TOÁN
CREATE TABLE THANHTOAN (
    MATHANHTOAN VARCHAR(20) PRIMARY KEY,
    MAHOADON INT NOT NULL,
    NGAYTHANHTOAN DATETIME NOT NULL,
    SOTIEN DECIMAL(18,2) NOT NULL,
    PHUONGTHUC NVARCHAR(50),
    TRANGTHAI NVARCHAR(50),
    CONSTRAINT FK_TT_HDVP FOREIGN KEY (MAHOADON) REFERENCES HOADONVIENPHI(MAHOADON)
);

-- Bảng NHẬP VIỆN
CREATE TABLE DIEUTRINOITRU (
	MANOITRU VARCHAR(10) PRIMARY KEY,
	MABN VARCHAR(10) NOT NULL,
	MABACSI VARCHAR(10),
	MAPHONG VARCHAR(10),
	NGAYNHAPVIEN DATETIME NOT NULL,
	NGAYXUATVIEN DATETIME,
	LYDONHAPVIEN NVARCHAR(MAX) NOT NULL,
	TINHTRANGRAVIEN NVARCHAR(255),
	CONSTRAINT FK_DTNT_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
	CONSTRAINT FK_DTNT_PHONGBENH FOREIGN KEY (MAPHONG) REFERENCES PHONGBENH(MAPHONG),
	CONSTRAINT FK_DTNT_BACSI FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_DTNT_LOAIPHONG FOREIGN KEY (MAPHONG) REFERENCES LOAIPHONG(MALOAIPHONG),
);

-- Bảng HỒ SƠ BỆNH ÁN --> gọi tắt là "hồ sơ" (HOSO)
CREATE TABLE HOSO (
	MAHS VARCHAR(10) PRIMARY KEY,
	MANOITRU VARCHAR(10) NOT NULL,
	MABN VARCHAR(10) NOT NULL,
	MABACSI VARCHAR(10) NOT NULL,
	CHUANDOAN NVARCHAR(MAX) NOT NULL,
	TRIEUCHUNG NVARCHAR(MAX) NOT NULL,
	KETLUAN NVARCAHR(MAX),
	HUONGDIEUTRI NVARCHAR(MAX),
	NGAYKHAM DATETIME NOT NULL,
	TRANGTHAIHOSO NVARCHAR(50),
	CONSTRAINT FK_HOSO_DTNT FOREIGN KEY (MANOITRU) REFERENCES DIEUTRINOITRU(MANOITRU),
	CONSTRAINT FK_HOSO_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
	CONSTRAINT FK_HOSO_NHANVIEN FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV)
);

-- Bảng LỊCH SỬ ĐIỀU TRỊ
CREATE TABLE LICHSUDIEUTRI (
    MALS VARCHAR(10) PRIMARY KEY,
    MAHS VARCHAR(10) NOT NULL,
    NGAYCAPNHAT DATETIME NOT NULL,
    NOIDUNG NVARCHAR(MAX) NOT NULL,
    MANV VARCHAR(10) NOT NULL,
    GHICHU NVARCHAR(255),
    CONSTRAINT FK_LSDT_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
    CONSTRAINT FK_LSDT_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bảng CHI TIẾT DỊCH VỤ
CREATE TABLE CHITIETDICHVU (
    MAHS VARCHAR(10) NOT NULL,
    MADV INT NOT NULL,
    NGAYTHUCHIEN DATETIME NOT NULL,
    KETQUA NVARCHAR(MAX),
    CHIPHI DECIMAL(18,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (MAHS, MADV), -- Khóa chính (hỗn hợp) 
    CONSTRAINT FK_CTDV_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
    CONSTRAINT FK_CTDV_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVUYTE(MADV)
);

-- Bảng TOA THUỐC
CREATE TABLE TOATHUOC (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATOA VARCHAR(10) NOT NULL,
	MAHS VARCHAR(10) NOT NULL,
	MATHUOC INT NOT NULL,
	SOLUONG INT NOT NULL,
	DONGIA DECIMAL(18,2) NOT NULL,
	THANHTIEN DECIMAL(18,2),
	LIEULUONG NVARCHAR(100) NOT NULL,
	CACHDUNG NVARCHAR(255),
	GHICHU NVARCHAR(MAX),
	CONSTRAINT FK_TOATHUOC_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
	CONSTRAINT FK_TOATHUOC_THUOC FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC),
);
