-- Thinh's

-- Bảng NHẬP VIỆN
CREATE TABLE DIEUTRINOITRU (
	MANOITRU VARCHAR(10) PRIMARY KEY,
	MABN VARCHAR(10) NOT NULL,
	MABACSI VARCHAR(10),
	MAPHONG INT NOT NULL,
	NGAYNHAPVIEN DATETIME NOT NULL,
	NGAYXUATVIEN DATETIME,
	LYDONHAPVIEN NVARCHAR(MAX) NOT NULL,
	TINHTRANGRAVIEN NVARCHAR(255),
	CONSTRAINT FK_DTNT_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
	CONSTRAINT FK_DTNT_PHONGBENH FOREIGN KEY (MAPHONG) REFERENCES PHONGBENH(MAPHONG),
	CONSTRAINT FK_DTNT_BACSI FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV),
);

-- Bảng HỒ SƠ BỆNH ÁN --> gọi tắt là "hồ sơ" (HOSO)
CREATE TABLE HOSO (
	MAHS VARCHAR(10) PRIMARY KEY,
	MANOITRU VARCHAR(10) NOT NULL,
	MABN VARCHAR(10) NOT NULL,
	MABACSI VARCHAR(10) NOT NULL,
	CHUANDOAN NVARCHAR(MAX) NOT NULL,
	TRIEUCHUNG NVARCHAR(MAX) NOT NULL,
	KETLUAN NVARCAHR(MAX),
	HUONGDIEUTRI NVARCHAR(MAX),
	NGAYKHAM DATETIME NOT NULL,
	TRANGTHAIHOSO NVARCHAR(50),
	CONSTRAINT FK_HOSO_DTNT FOREIGN KEY (MANOITRU) REFERENCES DIEUTRINOITRU(MANOITRU),
	CONSTRAINT FK_HOSO_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
	CONSTRAINT FK_HOSO_NHANVIEN FOREIGN KEY (MABACSI) REFERENCES NHANVIEN(MANV),
);

-- Bảng TOA THUỐC
CREATE TABLE TOATHUOC (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MATOA VARCHAR(10) NOT NULL,
	MAHS VARCHAR(10) NOT NULL,
	MATHUOC INT NOT NULL,
	SOLUONG INT NOT NULL,
	DONGIA DECIMAL(18,2) NOT NULL,
	THANHTIEN DECIMAL(18,2),
	LIEULUONG NVARCHAR(100) NOT NULL,
	CACHDUNG NVARCHAR(255),
	GHICHU NVARCHAR(MAX),
	CONSTRAINT FK_TOATHUOC_HOSO FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
	CONSTRAINT FK_TOATHUOC_THUOC FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC),
);