-- Tien's
create database QuanLyBenhVien;
use QuanLyBenhVien;
CREATE TABLE KHOA (
    MAKHOA INT NOT NULL,
    TENKHOA NVARCHAR(100) NOT NULL,
    VITRI NVARCHAR(100),
    SODIENTHOAI VARCHAR(15),
    TRUONGKHOA INT,
    NGAYTHANHLAP DATE,
    CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);

CREATE TABLE NHANVIEN (
    MANV INT NOT NULL,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(200),
    SODT VARCHAR(15),
    MAKHOA INT,
    CHUCVU NVARCHAR(50),
    CONSTRAINT PK_NV PRIMARY KEY (MANV),
    CONSTRAINT FK_NV_KHOA FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);

CREATE TABLE PHONGBENH (
    MAPHONG INT NOT NULL,
    TENPHONG NVARCHAR(100),
    LOAIPHONG NVARCHAR(50),
    MAKHOA INT,
    SUCCHUA INT,
    GIAPHONG DECIMAL(10,2),
    CONSTRAINT PK_PB PRIMARY KEY (MAPHONG),
    CONSTRAINT FK_PB_KHOA FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);
-- DO BẢNG NHANVIEN TẠO SAU BẢNG KHOA NÊN CẦN THÊM KHÓA NGOẠI SAU ĐÓ
-- NỐI KHOA(TRUONGKHOA) VỚI NHANVIEN(MANV)
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_TRUONGKHOA FOREIGN KEY (TRUONGKHOA)
REFERENCES NHANVIEN(MANV);