-- Tien's
create database QuanLyBenhVien;
use QuanLyBenhVien;
CREATE TABLE KHOA (
    MAKHOA VARCHAR(10) NOT NULL,
    TENKHOA NVARCHAR(100) NOT NULL,
    VITRI NVARCHAR(100),
    SODIENTHOAI VARCHAR(15),
    TRUONGKHOA VARCHAR(10),
    NGAYTHANHLAP DATE,
    EMAILKHOA VARCHAR(50),
    GHICHU NVARCHAR(50),
    CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR(10) NOT NULL,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    DIACHI NVARCHAR(200),
    SODT VARCHAR(15),
    MAKHOA VARCHAR(10),
    CHUCVU NVARCHAR(50),    
    EMAIL VARCHAR(50),
    NGAYVAOLAM DATE,
    BANGCAP VARCHAR(50),
    CHUYENMON VARCHAR(50),
    TRANGTHAI NVARCHAR(50),
    CONSTRAINT PK_NV PRIMARY KEY (MANV),
    CONSTRAINT FK_NV_KHOA FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);

CREATE TABLE PHONGBENH (
    MAPHONG INT IDENTITY(1,1) NOT NULL,
    TENPHONG NVARCHAR(100),
    LOAIPHONG NVARCHAR(50),
    MAKHOA VARCHAR(10),
    SUCCHUA INT,
    GIAPHONG DECIMAL(10,2),
    TRANGTHAI NVARCHAR(20),
    SOGIUONGTRONG INT,
    GHICHU NVARCHAR(50),
    CONSTRAINT PK_PB PRIMARY KEY (MAPHONG),
    CONSTRAINT FK_PB_KHOA FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);
-- DO BẢNG NHANVIEN TẠO SAU BẢNG KHOA NÊN CẦN THÊM KHÓA NGOẠI SAU ĐÓ
-- NỐI KHOA(TRUONGKHOA) VỚI NHANVIEN(MANV)
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_TRUONGKHOA FOREIGN KEY (TRUONGKHOA)
REFERENCES NHANVIEN(MANV);

ALTER TABLE KHOA
ALTER COLUMN MAKHOA VARCHAR(10) NOT NULL;
ALTER TABLE KHOA
ALTER COLUMN TRUONGKHOA VARCHAR(10);

ALTER TABLE NHANVIEN
ALTER COLUMN MANV VARCHAR(10) NOT NULL;
ALTER TABLE NHANVIEN
ALTER COLUMN MAKHOA NVARCHAR(10)

ALTER TABLE PHONGBENH
ALTER COLUMN MAKHOA VARCHAR(10);

-- Thêm bảng
CREATE TABLE CHITIETVIENPHI (
    MAHOADON INT NOT NULL,
    LOAICHIPHI NVARCHAR(100) NOT NULL,
    SOTIEN DECIMAL(14,2),
    MOTA NVARCHAR(255),

    PRIMARY KEY (MAHOADON, LOAICHIPHI),
    FOREIGN KEY (MAHOADON) REFERENCES HOADONVIENPHI(MAHOADON)
);
CREATE TABLE LICHHENKHAM (
    MALICHHEN INT NOT NULL,
    MABN INT,
    MABACSI INT,
    NGAYHEN DATE,
    GIOHEN TIME,
    TRANGTHAI NVARCHAR(50),
    GHICHU NVARCHAR(255),

    PRIMARY KEY (MALICHHEN),
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    FOREIGN KEY (MABACSI) REFERENCES BACSI(MABACSI)
);
CREATE TABLE DICHVUYTE (
    MADV INT NOT NULL,
    TENDV NVARCHAR(150),
    DONGIA DECIMAL(12,2),
    MOTA NVARCHAR(255),
    TRANGTHAI NVARCHAR(50),
    
    PRIMARY KEY (MADV)
);